name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libffi-dev \
          zlib1g-dev \
          libssl-dev \
          libbz2-dev \
          libreadline-dev \
          libsqlite3-dev \
          libncurses5-dev \
          libncursesw5-dev \
          xz-utils \
          tk-dev \
          liblzma-dev \
          openjdk-8-jdk \
          unzip \
          zip \
          wget \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libx11-dev \
          libxext-dev \
          libxrender-dev \
          libgstreamer1.0-dev \
          libpango1.0-dev \
          libmysqlclient-dev \
          libltdl-dev \
          autoconf \
          automake \
          pkg-config \
          libunwind-dev \
          libxml2-dev \
          libxslt1-dev \
          libpng-dev \
          libjpeg-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install \
          buildozer \
          cython==0.29.36 \
          appdirs \
          "colorama>=0.3.3" \
          "jinja2" \
          "sh>=1.10,<2.0" \
          build \
          toml \
          packaging \
          setuptools \
          kivy==2.3.0

    - name: Initialize Buildozer
      run: |
        if [ ! -f buildozer.spec ]; then buildozer init; fi
        sed -i 's/requirements = .*/requirements = python3,kivy==2.3.0/' buildozer.spec
        sed -i 's/android.api
