name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libffi-dev \
          zlib1g-dev \
          libssl-dev \
          libbz2-dev \
          libreadline-dev \
          libsqlite3-dev \
          libncurses5-dev \
          libncursesw5-dev \
          xz-utils \
          tk-dev \
          liblzma-dev \
          unzip \
          zip \
          wget \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libx11-dev \
          libxext-dev \
          libxrender-dev \
          libgstreamer1.0-dev \
          libpango1.0-dev \
          libmysqlclient-dev \
          libltdl-dev \
          autoconf \
          automake \
          pkg-config \
          libunwind-dev \
          libxml2-dev \
          libxslt1-dev \
          libpng-dev \
          libjpeg-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.36 kivy==2.3.0

    - name: Initialize Buildozer
      run: |
        if [ ! -f buildozer.spec ]; then buildozer init; fi
        sed -i "s|^requirements =.*|requirements = python3,kivy==2.3.0|" buildozer.spec
        sed -i "s|^android.api =.*|android.api = 31|" buildozer.spec
        sed -i "s|^android.minapi =.*|android.minapi = 21|" buildozer.spec
        sed -i "s|^log_level =.*|log_level = 2|" buildozer.spec
        sed -i "s|^package.name =.*|package.name = mydatabaseapp|" buildozer.spec
        sed -i "s|^version =.*|version = 0.1|" buildozer.spec

    - name: Set up Android SDK
      run: |
        mkdir -p /home/runner/.buildozer/android/platform/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9474226_latest.zip -O commandlinetools.zip
        unzip -q commandlinetools.zip -d /home/runner/.buildozer/android/platform/android-sdk
        rm commandlinetools.zip
        yes | /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/home/runner/.buildozer/android/platform/android-sdk "build-tools;36.0.0" "platform-tools"

    - name: Build APK
      run: |
        buildozer android debug
        if [ ! -f bin/mydatabaseapp-0.1-debug.apk ]; then
          echo "ERROR: APK not found at bin/mydatabaseapp-0.1-debug.apk"
          exit 1
        fi

    - name: Debug APK Location
      run: |
        echo "Listing bin directory contents:"
        ls -la bin/
        echo "Listing all APKs in bin directory:"
        find bin -name "*.apk"
        echo "Searching for APKs in the entire workspace:"
        find . -name "*.apk"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mydatabaseapp-apk
        path: bin/*.apk
