name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libffi-dev \
          zlib1g-dev \
          libssl-dev \
          libbz2-dev \
          libreadline-dev \
          libsqlite3-dev \
          libncurses5-dev \
          libncursesw5-dev \
          xz-utils \
          tk-dev \
          liblzma-dev \
          openjdk-8-jdk \
          unzip \
          zip \
          wget \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libx11-dev \
          libxext-dev \
          libxrender-dev \
          libgstreamer1.0-dev \
          libpango1.0-dev \
          libmysqlclient-dev \
          libltdl-dev \
          autoconf \
          automake \
          pkg-config \
          libunwind-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install \
          buildozer \
          cython==0.29.36 \
          appdirs \
          "colorama>=0.3.3" \
          "jinja2" \
          "sh>=1.10,<2.0" \
          build \
          toml \
          packaging \
          setuptools \
          kivy==2.3.0

    - name: Initialize Buildozer
      run: |
        buildozer init
        sed -i 's/requirements = .*/requirements = python3,kivy==2.3.0/' buildozer.spec
        sed -i 's/android.api = .*/android.api = 31/' buildozer.spec
        sed -i 's/android.minapi = .*/android.minapi = 21/' buildozer.spec
        sed -i 's/log_level = .*/log_level = 2/' buildozer.spec

    - name: Build APK
      run: |
        for i in {1..3}; do buildozer android debug && break || { echo "Retry $i/3"; sleep 10; }; done || { echo "Build failed after 3 retries"; exit 1; }
      env:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64

    - name: Debug APK Location
      run: |
        echo "Listing bin directory contents:"
        ls -la bin/
        echo "Listing all APKs in bin directory:"
        find bin -name "*.apk"

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mydatabaseapp-apk
        path: bin/*.apk
      continue-on-error: true
